version: '3.3'

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    command: mongod --bind_ip_all --auth
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  bot:
    build: .
    restart: always
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config.json:/app/config.json
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MSC_DONATE_METHOD=invoice
      - PROVIDER_TOKEN=""
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - MONGO_POOL_MIN=3

volumes:
  mongo_data:
